version: '3'
services:
  database:
    image: mongo:4.2
    container_name: 'mongodb-container'
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet

  spring-kotlin-chat-app:
    image: "simonenkoi/spring-kotlin-chat-exampole:0.0.1-SNAPSHOT"
    ports:
      - "8080:8080"
    command: ["java","-jar","-Dspring.profiles.active=local", "/opt/${SERVICE_NAME}/app.jar"]
    depends_on:
      - database
